---
title: "Reproducible Research: Peer Assessment 1"
author: "Ehsan Pourhadi"
date: "July 31, 2018"
output: 
  html_document:
    keep_md: true
---

The aim of the project is to answer a series of questions using data collected from [Fitbit](http://www.fitbit.com), [Nike
Fuelband](http://www.nike.com/us/en_us/c/nikeplus-fuelband), or [Jawbone Up](https://jawbone.com/up).

##Structure of this assignment 
i.Code for reading in the dataset and/or processing the data
ii.Histogram of the total number of steps taken each day
iii.Mean and median number of steps taken each day
iv.Time series plot of the average number of steps taken
v.The 5-minute interval that, on average, contains the maximum number of steps
vi.Code to describe and show a strategy for imputing missing data
vii.Histogram of the total number of steps taken each day after missing values are imputed
viii.Panel plot comparing the average number of steps taken per 5-minute interval across weekdays and weekends
ix.All of the R code needed to reproduce the results (numbers, plots, etc.) in the report

## Loading and preprocessing the data



## What is mean total number of steps taken per day?



## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
